# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_window.ui'
#
# Created: Thu Mar 16 17:43:07 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Calibration(object):
    def setupUi(self, Calibration):
        Calibration.setObjectName(_fromUtf8("Calibration"))
        Calibration.resize(538, 569)
        self.groupBox = QtGui.QGroupBox(Calibration)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 471, 421))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(10, 110, 451, 301))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 451, 22))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.starthourBox = QtGui.QComboBox(self.layoutWidget)
        self.starthourBox.setObjectName(_fromUtf8("starthourBox"))
        self.starthourBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.starthourBox)
        self.startminuteBox = QtGui.QComboBox(self.layoutWidget)
        self.startminuteBox.setObjectName(_fromUtf8("startminuteBox"))
        self.startminuteBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.startminuteBox)
        self.endhourBox = QtGui.QComboBox(self.layoutWidget)
        self.endhourBox.setObjectName(_fromUtf8("endhourBox"))
        self.endhourBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.endhourBox)
        self.endminuteBox = QtGui.QComboBox(self.layoutWidget)
        self.endminuteBox.setObjectName(_fromUtf8("endminuteBox"))
        self.endminuteBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.endminuteBox)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 451, 25))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.nodeBox = QtGui.QComboBox(self.layoutWidget1)
        self.nodeBox.setEditable(False)
        self.nodeBox.setObjectName(_fromUtf8("nodeBox"))
        self.nodeBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.nodeBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.sensorBox = QtGui.QComboBox(self.layoutWidget1)
        self.sensorBox.setObjectName(_fromUtf8("sensorBox"))
        self.sensorBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.sensorBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.channelBox = QtGui.QComboBox(self.layoutWidget1)
        self.channelBox.setObjectName(_fromUtf8("channelBox"))
        self.channelBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.channelBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 451, 25))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.loadNodeButton = QtGui.QPushButton(self.widget)
        self.loadNodeButton.setObjectName(_fromUtf8("loadNodeButton"))
        self.horizontalLayout_6.addWidget(self.loadNodeButton)
        self.nodeEdit = QtGui.QLineEdit(self.widget)
        self.nodeEdit.setObjectName(_fromUtf8("nodeEdit"))
        self.horizontalLayout_6.addWidget(self.nodeEdit)
        self.groupBox_2 = QtGui.QGroupBox(Calibration)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 470, 471, 61))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 461, 25))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.nodeButton = QtGui.QPushButton(self.layoutWidget2)
        self.nodeButton.setObjectName(_fromUtf8("nodeButton"))
        self.horizontalLayout_5.addWidget(self.nodeButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.exportRangeBox = QtGui.QComboBox(self.layoutWidget2)
        self.exportRangeBox.setObjectName(_fromUtf8("exportRangeBox"))
        self.exportRangeBox.addItem(_fromUtf8(""))
        self.exportRangeBox.addItem(_fromUtf8(""))
        self.exportRangeBox.addItem(_fromUtf8(""))
        self.exportRangeBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.exportRangeBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.layoutWidget3 = QtGui.QWidget(Calibration)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 540, 471, 25))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.pushButton = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton.setEnabled(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.layoutWidget4 = QtGui.QWidget(Calibration)
        self.layoutWidget4.setGeometry(QtCore.QRect(40, 10, 461, 25))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.openButton = QtGui.QPushButton(self.layoutWidget4)
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.horizontalLayout_2.addWidget(self.openButton)
        self.fileEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.fileEdit.setObjectName(_fromUtf8("fileEdit"))
        self.horizontalLayout_2.addWidget(self.fileEdit)

        self.retranslateUi(Calibration)
        QtCore.QObject.connect(self.openButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Calibration.openxlsx)
        QtCore.QObject.connect(self.nodeBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.setSensorBox)
        QtCore.QObject.connect(self.sensorBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.setChannelBox)
        QtCore.QObject.connect(self.channelBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.getColumnIndex)
        QtCore.QObject.connect(self.starthourBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.setStartminute)
        QtCore.QObject.connect(self.startminuteBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.setEndhour)
        QtCore.QObject.connect(self.endhourBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.setEndminute)
        QtCore.QObject.connect(self.endminuteBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.updateCanvas)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Calibration.calculateLeastsq)
        QtCore.QObject.connect(self.nodeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Calibration.getName)
        QtCore.QObject.connect(self.exportRangeBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.getRange)
        QtCore.QObject.connect(self.channelBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.enableGroup2)
        QtCore.QObject.connect(self.fileEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Calibration.enableGroup1)
        QtCore.QObject.connect(self.loadNodeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Calibration.openStandardDialog)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Calibration.openCalDialog)
        QtCore.QObject.connect(self.nodeEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Calibration.openStandard)
        QtCore.QObject.connect(self.exportRangeBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Calibration.enableButton)
        QtCore.QMetaObject.connectSlotsByName(Calibration)

    def retranslateUi(self, Calibration):
        Calibration.setWindowTitle(_translate("Calibration", "Calibration", None))
        self.groupBox.setTitle(_translate("Calibration", "标准结点选取", None))
        self.starthourBox.setItemText(0, _translate("Calibration", "--开始（小时）", None))
        self.startminuteBox.setItemText(0, _translate("Calibration", "--开始（分钟）", None))
        self.endhourBox.setItemText(0, _translate("Calibration", "--结束（小时）", None))
        self.endminuteBox.setItemText(0, _translate("Calibration", "--结束（分钟）", None))
        self.nodeBox.setItemText(0, _translate("Calibration", "--请选择结点", None))
        self.sensorBox.setItemText(0, _translate("Calibration", "--请选择传感器", None))
        self.channelBox.setItemText(0, _translate("Calibration", "--请选择通道", None))
        self.loadNodeButton.setText(_translate("Calibration", "从其他文件加载", None))
        self.groupBox_2.setTitle(_translate("Calibration", "输出选项", None))
        self.nodeButton.setText(_translate("Calibration", "--请选择结点", None))
        self.exportRangeBox.setItemText(0, _translate("Calibration", "--请选择通道", None))
        self.exportRangeBox.setItemText(1, _translate("Calibration", "全部", None))
        self.exportRangeBox.setItemText(2, _translate("Calibration", "只可见光", None))
        self.exportRangeBox.setItemText(3, _translate("Calibration", "只近红外", None))
        self.pushButton.setText(_translate("Calibration", "校准参数计算", None))
        self.pushButton_2.setText(_translate("Calibration", "校准新测量值", None))
        self.openButton.setText(_translate("Calibration", "打开表格", None))

